# Generated by Django 3.0.6 on 2020-12-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201210_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='player_id',
            field=models.IntegerField(),
        ),
    ]
