# Generated by Django 3.0.6 on 2020-12-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201211_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='player_id',
            field=models.CharField(max_length=50),
        ),
    ]
