# Generated by Django 3.0.6 on 2020-12-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201211_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersids',
            name='name',
            field=models.CharField(default=False, max_length=50, unique=True),
        ),
    ]
