# Generated by Django 3.0.6 on 2020-12-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201211_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersids',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
