# Generated by Django 3.0.6 on 2020-12-16 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201216_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersids',
            old_name='name',
            new_name='player_name',
        ),
    ]
