# Generated by Django 3.0.6 on 2020-12-21 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201221_0056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersIdss',
            new_name='UsersIds',
        ),
    ]
