# Generated by Django 3.0.6 on 2020-12-21 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201221_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SteamId',
        ),
        migrations.AddField(
            model_name='usersids',
            name='playersteam_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
