# Generated by Django 3.0.6 on 2020-12-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201221_1537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersIds',
            new_name='UsersId',
        ),
    ]
