# Generated by Django 3.0.6 on 2020-12-22 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201221_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersid',
            old_name='playersNameGive',
            new_name='players_name_given',
        ),
    ]
