# Generated by Django 3.0.6 on 2020-12-22 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201222_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersid',
            old_name='players_name_given',
            new_name='player_name_given',
        ),
    ]
